// src/App.jsx
import React, { useState, useEffect } from 'react';
import { Plus, Settings, CreditCard, Wallet } from 'lucide-react';
import SubscriptionCard from './components/SubscriptionCard';
import SubscriptionForm from './components/SubscriptionForm';
import TotalExpense from './components/TotalExpense';
import SettingsModal from './components/SettingsModal';
import { generateId } from './utils/uuid';
import { checkAndSendReminders } from './services/ReminderChecker';

function App() {
  // --- State Management ---
  const [subscriptions, setSubscriptions] = useState(() => {
    const saved = localStorage.getItem('remindyoursubs_subscriptions');
    return saved ? JSON.parse(saved) : [];
  });

  const [config, setConfig] = useState(() => {
    const saved = localStorage.getItem('remindyoursubs_config');
    const envApiKey = import.meta.env.VITE_RESEND_API_KEY;

    // Always prefer env var if available for security, or fallback to saved (though we are removing UI)
    const initialConfig = saved ? JSON.parse(saved) : {
      userEmail: '',
      reminderDaysBefore: 3
    };

    // Force overwrite API Key with Env Var if it exists
    if (envApiKey) {
      initialConfig.resendApiKey = envApiKey;
    }

    return initialConfig;
  });

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [editingSub, setEditingSub] = useState(null);
  const [toast, setToast] = useState({ show: false, message: '', type: '' });

  // --- Effects ---

  // Persist Subscriptions
  useEffect(() => {
    localStorage.setItem('remindyoursubs_subscriptions', JSON.stringify(subscriptions));
  }, [subscriptions]);

  // Persist Config
  useEffect(() => {
    localStorage.setItem('remindyoursubs_config', JSON.stringify(config));
  }, [config]);

  // Check Reminders on Mount & Config Change
  useEffect(() => {
    const runCheck = async () => {
      await checkAndSendReminders(subscriptions, config, (updatedSubs) => {
        // Merge updates
        setSubscriptions(prev => {
          return prev.map(sub => {
            const update = updatedSubs.find(u => u.id === sub.id);
            return update ? update : sub;
          });
        });
        showToast(`Email reminder sent for ${updatedSubs.length} subscriptions!`, 'success');
      });
    };

    runCheck();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config.userEmail, config.reminderDaysBefore]); // API Key is now static from env usually

  // --- Handlers ---

  const showToast = (message, type = 'success') => {
    setToast({ show: true, message, type });
    setTimeout(() => setToast({ show: false, message: '', type: '' }), 3000);
  };

  const handleSaveSubscription = (data) => {
    if (editingSub) {
      setSubscriptions(subscriptions.map(sub =>
        sub.id === editingSub.id ? { ...sub, ...data } : sub
      ));
      showToast('Langganan berhasil diperbarui');
    } else {
      setSubscriptions([...subscriptions, {
        id: generateId(),
        ...data,
        isActive: true,
        reminderEnabled: true,
        lastReminderSent: null
      }]);
      showToast('Langganan baru ditambahkan');
    }
    setIsFormOpen(false);
    setEditingSub(null);
  };

  const handleDelete = (id) => {
    if (window.confirm('Yakin ingin menghapus langganan ini?')) {
      setSubscriptions(subscriptions.filter(sub => sub.id !== id));
      showToast('Langganan dihapus', 'info');
    }
  };

  const handleEdit = (sub) => {
    setEditingSub(sub);
    setIsFormOpen(true);
  };

  const handleToggleReminder = (id) => {
    setSubscriptions(subscriptions.map(sub =>
      sub.id === id ? { ...sub, reminderEnabled: !sub.reminderEnabled } : sub
    ));
  };

  const handleSaveConfig = (newConfig) => {
    setConfig(newConfig);
    showToast('Pengaturan disimpan');
  };

  return (
    <div className="min-h-screen bg-zinc-900 text-white font-sans selection:bg-blue-500 selection:text-white">
      {/* Toast Notification */}
      {toast.show && (
        <div className={`fixed top-4 right-4 z-50 px-4 py-2 rounded-lg shadow-lg transform transition-all animate-bounce-in ${toast.type === 'error' ? 'bg-red-600' : 'bg-green-600'
          }`}>
          {toast.message}
        </div>
      )}

      {/* Navbar */}
      <nav className="border-b border-zinc-800 bg-zinc-900/50 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="bg-blue-600 p-2 rounded-lg">
              <CreditCard className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight">RemindYourSubs</h1>
          </div>
          <button
            onClick={() => setIsSettingsOpen(true)}
            className="p-2 hover:bg-zinc-800 rounded-lg text-gray-400 hover:text-white transition-colors"
          >
            <Settings className="w-5 h-5" />
          </button>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h1 className="text-3xl font-bold text-white mb-2">Dashboard Langganan</h1>
            <p className="text-gray-400">Kelola semua tagihan bulananmu di satu tempat.</p>
          </div>

          {!isFormOpen && (
            <button
              onClick={() => { setEditingSub(null); setIsFormOpen(true); }}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-all shadow-lg shadow-blue-900/20 flex items-center"
            >
              <Plus className="w-5 h-5 mr-2" />
              Tambah Langganan
            </button>
          )}
        </div>

        {/* Stats Section */}
        <TotalExpense subscriptions={subscriptions} />

        {/* Form Section */}
        {isFormOpen && (
          <SubscriptionForm
            initialData={editingSub}
            onSave={handleSaveSubscription}
            onCancel={() => { setIsFormOpen(false); setEditingSub(null); }}
          />
        )}

        {/* Subscriptions Grid */}
        {subscriptions.length === 0 && !isFormOpen ? (
          <div className="text-center py-20 bg-zinc-800/50 rounded-lg border border-zinc-800 border-dashed">
            <div className="bg-zinc-800 inline-flex p-4 rounded-full mb-4">
              <Wallet className="w-8 h-8 text-gray-500" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">Belum ada langganan</h3>
            <p className="text-gray-400 mb-6">Mulai catat pengeluaran bulananmu sekarang.</p>
            <button
              onClick={() => setIsFormOpen(true)}
              className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
            >
              Tambah Pertama
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {subscriptions.map(sub => (
              <SubscriptionCard
                key={sub.id}
                subscription={sub}
                onEdit={handleEdit}
                onDelete={handleDelete}
                onToggleReminder={handleToggleReminder}
              />
            ))}
          </div>
        )}
      </main>

      {/* Modals */}
      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
        config={config}
        onSave={handleSaveConfig}
      />
    </div>
  );
}

export default App;

// assignment/frontend-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription, SubscriptionRequest } from './models/subscription.model';
import { MonthlyExpense } from './models/monthly-expense.model';
import { SubscriptionService } from './services/subscription.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  subscriptions: Subscription[] = [];
  monthlyExpense: MonthlyExpense | null = null;
  isFormOpen = false;
  editingSubscription: Subscription | null = null;

  formData: SubscriptionRequest = {
    userId: 1,
    name: '',
    price: 0,
    billingDate: new Date().getDate()
  };

  toast = {
    show: false,
    message: '',
    type: 'success' as 'success' | 'error'
  };

  private userId = 1; // Hardcoded for single-user system

  constructor(private subscriptionService: SubscriptionService) { }

  ngOnInit() {
    this.loadSubscriptions();
    this.loadMonthlyExpense();
  }

  loadSubscriptions() {
    this.subscriptionService.getSubscriptionsByUserId(this.userId).subscribe({
      next: (data) => {
        this.subscriptions = data;
      },
      error: (error) => {
        console.error('Error loading subscriptions:', error);
        this.showToast('Gagal memuat data langganan', 'error');
      }
    });
  }

  loadMonthlyExpense() {
    this.subscriptionService.getMonthlyExpense(this.userId).subscribe({
      next: (data) => {
        this.monthlyExpense = data;
      },
      error: (error) => {
        console.error('Error loading monthly expense:', error);
      }
    });
  }

  openAddForm() {
    this.editingSubscription = null;
    this.isFormOpen = true;
  }

  openEditForm(subscription: Subscription) {
    this.editingSubscription = subscription;
    this.formData = {
      userId: this.userId,
      name: subscription.name,
      price: subscription.price,
      billingDate: subscription.billingDate
    };
    this.isFormOpen = true;
  }

  closeForm() {
    this.isFormOpen = false;
    this.editingSubscription = null;
    this.formData = {
      userId: this.userId,
      name: '',
      price: 0,
      billingDate: new Date().getDate()
    };
  }

  handleSaveSubscription(formData: SubscriptionRequest) {
    if (this.editingSubscription && this.editingSubscription.id) {
      // Update existing
      this.subscriptionService.updateSubscription(this.editingSubscription.id, formData).subscribe({
        next: () => {
          this.showToast('Langganan berhasil diperbarui');
          this.loadSubscriptions();
          this.loadMonthlyExpense();
          this.closeForm();
        },
        error: (error) => {
          console.error('Error updating subscription:', error);
          this.showToast('Gagal memperbarui langganan', 'error');
        }
      });
    } else {
      // Create new
      this.subscriptionService.createSubscription(formData).subscribe({
        next: () => {
          this.showToast('Langganan baru ditambahkan');
          this.loadSubscriptions();
          this.loadMonthlyExpense();
          this.closeForm();
        },
        error: (error) => {
          console.error('Error creating subscription:', error);
          this.showToast('Gagal menambahkan langganan', 'error');
        }
      });
    }
  }

  handleDeleteSubscription(id: number) {
    if (confirm('Yakin ingin menghapus langganan ini?')) {
      this.subscriptionService.deleteSubscription(id).subscribe({
        next: () => {
          this.showToast('Langganan dihapus');
          this.loadSubscriptions();
          this.loadMonthlyExpense();
        },
        error: (error) => {
          console.error('Error deleting subscription:', error);
          this.showToast('Gagal menghapus langganan', 'error');
        }
      });
    }
  }

  handleToggleReminder(id: number) {
    this.subscriptionService.toggleReminder(id).subscribe({
      next: () => {
        this.loadSubscriptions();
      },
      error: (error) => {
        console.error('Error toggling reminder:', error);
        this.showToast('Gagal mengubah pengingat', 'error');
      }
    });
  }

  showToast(message: string, type: 'success' | 'error' = 'success') {
    this.toast = { show: true, message, type };
    setTimeout(() => {
      this.toast.show = false;
    }, 3000);
  }

  calculateDaysUntilBilling(billingDate: number): number {
    const today = new Date();
    const currentDay = today.getDate();
    const currentMonth = today.getMonth();
    const currentYear = today.getFullYear();

    let nextBillingDate: Date;

    if (billingDate >= currentDay) {
      nextBillingDate = new Date(currentYear, currentMonth, billingDate);
    } else {
      nextBillingDate = new Date(currentYear, currentMonth + 1, billingDate);
    }

    const diffTime = nextBillingDate.getTime() - today.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    return diffDays;
  }

  getStatusColor(daysLeft: number): string {
    if (daysLeft <= 3) {
      return 'bg-red-900/30 text-red-400';
    } else if (daysLeft <= 7) {
      return 'bg-yellow-900/30 text-yellow-400';
    } else {
      return 'bg-green-900/30 text-green-400';
    }
  }

  getStatusLabel(daysLeft: number): string {
    if (daysLeft === 0) {
      return 'Hari Ini';
    } else if (daysLeft === 1) {
      return 'Besok';
    } else if (daysLeft < 0) {
      return 'Lewat';
    } else {
      return `${daysLeft} Hari`;
    }
  }
}

<!-- Toast Notification -->
<div *ngIf="toast.show" [class]="'fixed top-4 right-4 z-50 px-4 py-2 rounded-lg shadow-lg transform transition-all animate-bounce-in ' + 
              (toast.type === 'error' ? 'bg-red-600' : 'bg-green-600')">
  {{ toast.message }}
</div>

<!-- Main Container -->
<div class="min-h-screen bg-zinc-900 text-white font-sans selection:bg-blue-500 selection:text-white">

  <!-- Navbar -->
  <nav class="border-b border-zinc-800 bg-zinc-900/50 backdrop-blur-md sticky top-0 z-40">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
      <div class="flex items-center space-x-2">
        <div class="bg-blue-600 p-2 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
          </svg>
        </div>
        <h1 class="text-xl font-bold tracking-tight">RemindYourSubs</h1>
      </div>
    </div>
  </nav>

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

    <!-- Header Section -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
      <div>
        <h1 class="text-3xl font-bold text-white mb-2">Dashboard Langganan</h1>
        <p class="text-gray-400">Kelola semua tagihan bulananmu di satu tempat.</p>
      </div>

      <button *ngIf="!isFormOpen" (click)="openAddForm()"
        class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-all shadow-lg shadow-blue-900/20 flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24"
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        Tambah Langganan
      </button>
    </div>

    <!-- Total Expense Card -->
    <div *ngIf="monthlyExpense"
      class="bg-zinc-800 rounded-lg p-6 shadow-lg border border-zinc-700 flex flex-col items-center justify-center mb-8">
      <h3 class="text-gray-400 text-sm font-medium uppercase tracking-wider mb-2">Total Pengeluaran Bulanan</h3>
      <div class="text-4xl font-bold text-white">
        Rp {{ monthlyExpense.totalExpense.toLocaleString('id-ID') }}
      </div>
    </div>

    <!-- Subscription Form -->
    <div *ngIf="isFormOpen" class="bg-zinc-800 rounded-lg p-6 shadow-lg border border-zinc-700 mb-8 animate-fade-in">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-xl font-bold text-white">
          {{ editingSubscription ? 'Edit Langganan' : 'Tambah Langganan Baru' }}
        </h2>
        <button (click)="closeForm()" class="text-gray-400 hover:text-white">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <form (ngSubmit)="handleSaveSubscription(formData)" #subscriptionForm="ngForm" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-400 mb-1">Nama Layanan</label>
          <input type="text" name="name" [(ngModel)]="formData.name" placeholder="Contoh: Netflix Premium"
            class="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-3 text-white focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition-all placeholder-gray-600"
            required>
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">Harga (Rp)</label>
            <input type="number" name="price" [(ngModel)]="formData.price" placeholder="186000"
              class="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-3 text-white focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition-all placeholder-gray-600"
              required min="0">
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">Tanggal Tagihan (1-31)</label>
            <input type="number" name="billingDate" [(ngModel)]="formData.billingDate" min="1" max="31"
              class="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-3 text-white focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition-all placeholder-gray-600"
              required>
          </div>
        </div>

        <div class="flex justify-end pt-4 space-x-3">
          <button type="button" (click)="closeForm()"
            class="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg font-medium transition-colors">
            Batal
          </button>
          <button type="submit" [disabled]="!subscriptionForm.form.valid"
            class="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors flex items-center shadow-lg shadow-blue-900/20 disabled:opacity-50">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
            </svg>
            Simpan
          </button>
        </div>
      </form>
    </div>

    <!-- Empty State -->
    <div *ngIf="subscriptions.length === 0 && !isFormOpen"
      class="text-center py-20 bg-zinc-800/50 rounded-lg border border-zinc-800 border-dashed">
      <div class="bg-zinc-800 inline-flex p-4 rounded-full mb-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-gray-500" fill="none" viewBox="0 0 24 24"
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
        </svg>
      </div>
      <h3 class="text-xl font-semibold text-white mb-2">Belum ada langganan</h3>
      <p class="text-gray-400 mb-6">Mulai catat pengeluaran bulananmu sekarang.</p>
      <button (click)="openAddForm()"
        class="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors">
        Tambah Pertama
      </button>
    </div>

    <!-- Subscriptions Grid -->
    <div *ngIf="subscriptions.length > 0" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div *ngFor="let subscription of subscriptions"
        class="bg-zinc-800 rounded-lg p-6 shadow-lg border border-zinc-700 hover:border-zinc-600 transition-colors group">

        <div class="flex justify-between items-start mb-4">
          <div>
            <h3 class="text-xl font-bold text-white mb-1 group-hover:text-blue-400 transition-colors">
              {{ subscription.name }}
            </h3>
            <p class="text-2xl font-semibold text-gray-200">
              Rp {{ subscription.price.toLocaleString('id-ID') }}
              <span class="text-sm text-gray-500 font-normal"> / bulan</span>
            </p>
          </div>

          <!-- Status Badge -->
          <span
            [class]="'px-2 py-1 rounded-md text-xs font-bold uppercase tracking-wider ' + getStatusColor(calculateDaysUntilBilling(subscription.billingDate))">
            {{ getStatusLabel(calculateDaysUntilBilling(subscription.billingDate)) }}
          </span>
        </div>

        <div class="flex justify-between items-end mt-4">
          <div class="text-sm text-gray-400">
            <p>Tagihan setiap tgl <span class="text-white font-medium">{{ subscription.billingDate }}</span></p>
            <div class="flex items-center mt-2 space-x-2">
              <button (click)="handleToggleReminder(subscription.id!)"
                [class]="'flex items-center text-xs font-medium px-2 py-1 rounded transition-colors ' + 
                         (subscription.reminderEnabled ? 'bg-green-900/30 text-green-400 hover:bg-green-900/50' : 'bg-zinc-700 text-gray-400 hover:bg-zinc-600')">
                <svg *ngIf="subscription.reminderEnabled" xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 mr-1"
                  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
                <svg *ngIf="!subscription.reminderEnabled" xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 mr-1"
                  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                </svg>
                {{ subscription.reminderEnabled ? 'Reminder ON' : 'Reminder OFF' }}
              </button>
            </div>
          </div>

          <div class="flex space-x-2">
            <button (click)="openEditForm(subscription)"
              class="p-2 text-gray-400 hover:text-white hover:bg-zinc-700 rounded-lg transition-colors" title="Edit">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
            </button>
            <button (click)="handleDeleteSubscription(subscription.id!)"
              class="p-2 text-gray-400 hover:text-red-400 hover:bg-red-900/20 rounded-lg transition-colors"
              title="Delete">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </button>
          </div>
        </div>

      </div>
    </div>

  </main>
</div>
